port: "8000"

db:
  username: "postgres"
  host: "localhost"
  port: "5432"
  dbname: "postgres"
  sslmode: "disable"

cntDayArchive: 3
periodicity: 600

openWeatherMap:
  unit: "C"
  lang: "en"

dbTables:
  subscription: subscription
  weather: weather
  weather_archive: weather_archive